name: resource
version: 1.0.1
description: Reading resource data from (package and other) files.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/resource

environment:
  sdk: '>=1.14.0-any <2.0.0'

dependencies:
  typed_data: "^1.0.0"
dev_dependencies:
  test: "^0.12.0"
