name: resource
version: 2.1.4
description: Reading resource data from (package and other) files.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/resource

environment:
  sdk: '>=2.0.0-dev.17.0 <2.0.0'

dependencies:
  typed_data: "^1.0.0"
dev_dependencies:
  test: "^0.12.0"
